title: Yarrboard
description: Open Hardware Marine Electronics
remote_theme: just-the-docs/just-the-docs@v0.10.1

url: ""
baseurl: ""

logo: "/logo.png"
favicon_ico: "/favicon.ico"
search_enabled: true
heading_anchors: true

nav_external_links:
  - title: Frothfet
    url: https://www.frothfet.com
  - title: Brineomatic
    url: https://www.brineomatic.com
  - title: Sendit
    url: https://sendit.yarrboard.com
  - title: Yarrboard Framework
    url: https://framework.yarrboard.com

aux_links:
  "GitHub":
    - "https://github.com/hoeken/yarrboard"

callouts:
  note:
    title: Note
    color: blue
  new:
    title: New
    color: green
  warning:
    title: Warning
    color: red

footer_content: "Yarrboard is an ecosystem of marine open hardware projects."

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/hoeken/yarrboard-website" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-remote-theme
